import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
from cvae import CVAE
from lstm_forecaster import LSTMForecaster
import matplotlib.pyplot as plt

def calculate_metrics(y_true, y_pred):
    # Mean Absolute Percentage Error (MAPE)
    # Adding epsilon to avoid division by zero
    epsilon = 1e-8
    mape = torch.mean(torch.abs((y_true - y_pred) / (y_true + epsilon))) * 100
    
    # Root Mean Squared Error (RMSE)
    rmse = torch.sqrt(torch.mean((y_true - y_pred) ** 2))
    
    return mape.item(), rmse.item()

def evaluate():
    """
    The core of the Black Swan Simulator.
    We take an LSTM trained ONLY on normal conditions, and we hit it with 
    synthetic Black Swan events generated by our CVAE to see how badly it breaks.
    """
    print("--- Running Black Swan Stress Test ---")
    
    # 1. Initialize models
    # Note: In a real scenario, you'd load the pre-trained weights here
    # cvae.load_state_dict(torch.load('cvae_model.pth'))
    # lstm.load_state_dict(torch.load('lstm_model.pth'))
    # For this demo script to run immediately, we'll instantiate them fresh.
    # If the user ran train_lstm.py, they can load the weights.
    
    cvae = CVAE(input_dim=28, num_classes=3, hidden_dim=32, latent_dim=4)
    lstm = LSTMForecaster()
    
    try:
        lstm.load_state_dict(torch.load("lstm_model.pth"))
        print("Loaded trained LSTM model.")
    except:
        print("Warning: No pre-trained LSTM weights found. Evaluating with initialized weights.")

    cvae.eval()
    lstm.eval()

    num_test_scenarios = 100
    
    # 2. Generate the Latent 'Core' Scenarios
    # We create 100 core underlying demand patterns
    z = torch.randn(num_test_scenarios, 4)
    
    results = []

    # 3. Test Across All Conditions
    conditions_map = {0: "Normal", 1: "Port Closure", 2: "Demand Spike"}
    
    for condition_idx, condition_name in conditions_map.items():
        # Create one-hot conditions
        c = torch.tensor([condition_idx] * num_test_scenarios)
        c_one_hot = F.one_hot(c, num_classes=3).float()
        
        # Ask CVAE to generate the demand sequences for this specific condition
        with torch.no_grad():
            generated_sequences = cvae.decode(z, c_one_hot)
            
        # The LSTM expects the first 21 days as input, to predict the last 7 days
        x_input = generated_sequences[:, :21].unsqueeze(2) # Shape: (100, 21, 1)
        y_true = generated_sequences[:, 21:]               # Shape: (100, 7)
        
        # Get LSTM Predictions
        with torch.no_grad():
            y_pred = lstm(x_input)
            
        # Calculate Metrics
        mape, rmse = calculate_metrics(y_true, y_pred)
        
        results.append({
            "Scenario": condition_name,
            "RMSE (Lower is better)": round(rmse, 4),
            "MAPE % (Lower is better)": round(mape, 2)
        })

    # 4. Display the Stress Test Results
    results_df = pd.DataFrame(results)
    print("\n" + "="*50)
    print("STRESS TEST RESULTS: MODEL DEGRADATION")
    print("="*50)
    print(results_df.to_string(index=False))
    print("="*50)
    
    print("\nInsight: Notice how the LSTM's error skyrockets during Black Swan events!")
    print("This proves the necessity of training robust models, and our CVAE provides the data to do it.")

if __name__ == "__main__":
    evaluate()
